rules:
- id: max-missing-except
  patterns:
    - pattern: max(...)
    - pattern-not-inside: |
        try:
            ...
        except:
            ...
    - pattern-not-inside: |
        try:
            ...
        except ValueError:
            ...
    - pattern-not-inside: |
        try:
            ...
        except ValueError as $E:
            ...
    - pattern-not-inside: |
        try:
            ...
        except Exception:
            ...
    - pattern-not-inside: |
        try:
            ...
        except Exception as $E:
            ...
  message: Call to 'max' throws 'ValueError' on empty iterable.
  languages:
  - python
  severity: ERROR
